import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import councilRouter from "./council";
import godmodeRouter from "./godmode";
import autotuneRouter from "./autotune";
import imageRouter from "./image";
import visionRouter from "./vision";
import agentRouter from "./agent";
import contextRouter from "./context";
import osintRouter from "./osint";
import claudeCodeRouter from "./claude-code";
import filesRouter from "./files";
import shellRouter from "./shell";
import gitRouter from "./git";
import providersRouter from "./providers";
import localProxyRouter from "./local-proxy";
import agent4Router from "./agent4";
import ollamaRouter from "./ollama";
import localEnginesRouter from "./local-engines";
import loadBalancerRouter from "./load-balancer";
// ── New feature routes ────────────────────────────────────────────────────────
import userAuthRouter from "./user-auth";
import stripeRouter from "./stripe";
import apiKeysRouter from "./api-keys";
import notificationsRouter from "./notifications";
import codeScanRouter from "./code-scan";
import reportsRouter from "./reports";
import swaggerRouter from "./swagger";
import finetuneRouter from "./finetune";
import pluginsRouter from "./plugins";
import ragRouter from "./rag";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(chatRouter);
router.use(councilRouter);
router.use(godmodeRouter);
router.use(autotuneRouter);
router.use(imageRouter);
router.use(visionRouter);
router.use(agentRouter);
router.use(contextRouter);
router.use(osintRouter);
router.use(claudeCodeRouter);
router.use(filesRouter);
router.use(shellRouter);
router.use(gitRouter);
router.use(providersRouter);
router.use(localProxyRouter);
router.use(agent4Router);
router.use(ollamaRouter);
router.use(localEnginesRouter);
router.use(loadBalancerRouter);
// ── New feature routes ────────────────────────────────────────────────────────
router.use(userAuthRouter);
router.use(stripeRouter);
router.use(apiKeysRouter);
router.use(notificationsRouter);
router.use(codeScanRouter);
router.use(reportsRouter);
router.use(swaggerRouter);
router.use(finetuneRouter);
router.use(pluginsRouter);
router.use(ragRouter);
router.use(adminRouter);

export default router;
